server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview?autoReconnect=true
    username: root
    password: qwerty
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql:   true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root:           WARN
    org:
      hibernate:    ERROR